force-app/main/default/objects/Leave_Application__c/Leave_Application__c.object-meta.xml
<CustomObject>
    <description>The Leave_Application__c object is designed to manage and track employee leave requests within an organization. This object facilitates the submission, approval, and monitoring of leave applications, ensuring that all leave-related activities are documented and processed efficiently. The object includes fields to specify the type of leave, duration, status, and ensures compliance with company policies and regulations, particularly within the context of a German work environment.</description>
    <label>Leave Application</label>
    <nameField>
        <displayFormat>APP-{0000}</displayFormat>
        <label>Leave Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leave Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Leave_Application__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <description>This field contains the duration</description>
    <label>Duration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Leave_Application__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <description>Specifies the end date of the leave period.</description>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Leave_Application__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <description>Specifies the start date of the leave period. Validation rules ensure that the start date cannot be set in the past.</description>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Leave_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Draft&quot;</defaultValue>
    <description>A picklist field to track the status of the leave application (Draft, In Progress, Approved, Not Approved). The default status is &quot;Draft,&quot; which is read-only.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Leave_Application__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the affected user of the Leave Record</description>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Leave_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/verivox/test/LeaveApplicationServiceTest.cls
@isTest
private class LeaveApplicationServiceTest {

    
    @isTest
    static void testGetLeaveApplicationsByEmail(){
        // Create a test user
        User testUser = new User(
            FirstName = 'Test',
            LastName = 'User',
            Email = 'testuser@example.com',
            Username = getDynamicUserNaiveEmail(),
            Alias = 'tuser',
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            ProfileId = [SELECT Id FROM Profile WHERE Name='Standard User'][0].Id,
            LanguageLocaleKey = 'en_US'
        );
        insert testUser;

        // Create a test leave application for the user
        Leave_Application__c testLeaveApp = new Leave_Application__c(
            User__c = testUser.Id,
            Start_Date__c = Date.newInstance(System.today().year(), 7, 24),
            End_Date__c = Date.newInstance(System.today().year(), 8, 13),
            Status__c = 'Approved',
            Duration__c = 15
        );
        insert testLeaveApp;

        // Simulate the REST request and response
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/leaveapplications';
        req.addParameter('email', 'testuser@example.com');
        req.addParameter('hub.verify_token', 'ABCDDDFFF');
        req.addParameter('hub.challenge', 'test');
        req.httpMethod = 'GET';

        RestContext.request = req;
        RestContext.response = res;

        // Call the REST service method
        List<Leave_Application__c> result = LeaveApplicationService.queryLeaveApplications(testUser.Email);

        System.debug(JSON.serializePretty(res));

        // Verify the response
        System.assertEquals(200, res.statusCode);
 
    }
    
    @isTest
    static void testGetLeaveApplicationsByEmailMissingEmail() {
        // Simulate the REST request and response
        RestRequest req = new RestRequest();
        req.requestURI = '/services/apexrest/leaveapplications';
        req.httpMethod = 'GET';
        RestContext.request = req;

        RestResponse res = new RestResponse();
        RestContext.response = res;

        System.debug(JSON.serializePretty(RestContext.response.statusCode));

        // Call the REST service method
        List<Leave_Application__c> result = LeaveApplicationService.getLeaveApplicationsByEmail();

        // Verify the response
        System.assertEquals(400, RestContext.response.statusCode);
        System.assertEquals('Missing email parameter', RestContext.response.responseBody.toString());
    }

    @isTest
    static void testGetLeaveApplicationsByEmailUserNotFound() {
        // Simulate the REST request and response
        RestRequest req = new RestRequest();
        req.requestURI = '/services/apexrest/leaveapplications';
        req.addParameter('email', 'nonexistent@example.com');
        req.httpMethod = 'GET';
        RestContext.request = req;

        RestResponse res = new RestResponse();
        RestContext.response = res;

        // Call the REST service method
        List<Leave_Application__c> result = LeaveApplicationService.getLeaveApplicationsByEmail();

        // Verify the response
        System.assertEquals(200, RestContext.response.statusCode);
        System.assertEquals(0, result.size());
    }

    static String getDynamicUserNaiveEmail() {
        return 'testuser' + String.valueOf(Math.abs(Crypto.getRandomInteger())) + '@example.com';
    }
}