force-app/main/default/objects/Leave_Application__c/Leave_Application__c.object-meta.xml
<CustomObject>
    <description>The Leave_Application__c object is designed to manage and track employee leave requests within an organization. This object facilitates the submission, approval, and monitoring of leave applications, ensuring that all leave-related activities are documented and processed efficiently. The object includes fields to specify the type of leave, duration, status, and ensures compliance with company policies and regulations, particularly within the context of a German work environment.</description>
    <label>Leave Application</label>
    <nameField>
        <displayFormat>APP-{0000}</displayFormat>
        <label>Leave Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leave Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Leave_Application__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <description>This field contains the duration</description>
    <label>Duration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Leave_Application__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <description>Specifies the end date of the leave period.</description>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Leave_Application__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <description>Specifies the start date of the leave period. Validation rules ensure that the start date cannot be set in the past.</description>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Leave_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Draft&quot;</defaultValue>
    <description>A picklist field to track the status of the leave application (Draft, In Progress, Approved, Not Approved). The default status is &quot;Draft,&quot; which is read-only.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Leave_Application__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the affected user of the Leave Record</description>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Leave_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/verivox/classes/LeaveApplicationService.cls
@RestResource(urlMapping='/leaveapplications/*')
global with sharing class LeaveApplicationService {
    
    @HttpGet
    global static List<Leave_Application__c> getLeaveApplicationsByEmail() {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;

        // Get the email parameter from the request
        String email = RestContext.request.params.get('email');

        // Check if the email parameter is provided
        if (email == null) {
            RestContext.response.statusCode = 400;
            RestContext.response.responseBody = Blob.valueOf('Missing email parameter');
            return null;
        }
        
        return queryLeaveApplications(email);
    }
    
    @TestVisible
    private static List<Leave_Application__c> queryLeaveApplications(String email) {
        // Get the current financial year
        Date startOfYear = Date.newInstance(System.today().year(), 1, 1);
        Date endOfYear = Date.newInstance(System.today().year(), 12, 31);

        // Query the user based on email
        List<User> users = [SELECT Id FROM User WHERE Email =: email];
        
        if (users.size() == 0) {
            return new List<Leave_Application__c>(); // Return empty list if user not found
        }

        user user = users[0];
        
        // Query leave applications for the user in the current financial year
        List<Leave_Application__c> leaveApplications = [SELECT Id, Start_Date__c, End_Date__c, Status__c, Duration__c
                                                        FROM Leave_Application__c
                                                        WHERE User__c = :user.Id
                                                        AND Start_Date__c >= :startOfYear
                                                        AND End_Date__c <= :endOfYear];
        
        return leaveApplications;
    }
}