force-app/main/default/objects/Leave_Policy_Config__mdt/Leave_Policy_Config__mdt.object-meta.xml
<CustomObject>
    <description>This custom metadata type stores configuration settings related to employee leave policies, including the total number of vacation days per year and the maximum allowable duration for a leave request.</description>
    <label>Leave Policy Config</label>
    <pluralLabel>Leave Policy Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Leave_Policy_Config__mdt/fields/MaximumLeaveDurationinDays__c.field-meta.xml
<CustomField>
    <fullName>MaximumLeaveDurationinDays__c</fullName>
    <description>Defines the maximum number of calendar weeks an employee can take off in a single leave request. For example, if employees cannot take more than 3 weeks off in a row, this field will hold the value 3 (21 days)</description>
    <label>Maximum Leave Duration in Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Leave_Policy_Config__mdt/fields/TotalVacationDaysPerYear__c.field-meta.xml
<CustomField>
    <fullName>TotalVacationDaysPerYear__c</fullName>
    <description>Specifies the total number of vacation days each employee is entitled to per year. For example, if employees are entitled to 30 days of vacation per year, this field will hold the value 30.</description>
    <label>Total Vacation Days Per Year</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User/fields/Leftover_Vacation__c.field-meta.xml
<CustomField>
    <fullName>Leftover_Vacation__c</fullName>
    <defaultValue>0</defaultValue>
    <description>This is the leftover vacation based on the TotalVacationDaysPerYear__c field</description>
    <label>Leftover Vacation</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/verivox/classes/ERPIntegrationService.cls
public class ERPIntegrationService {
    
    @future(callout=true)
    public static void updateVacationBalance(Set<Id> userIds) {

        // Get user records
        Map<Id, User> usersMap = new Map<Id, User>([SELECT Id, Email, Leftover_Vacation__c 
                                                    FROM User WHERE Id IN :userIds]);
        // Create JSON payload for all users
        List<Map<String, Object>> userPayloads = new List<Map<String, Object>>();
        for (User user : usersMap.values()) {
            Map<String, Object> userPayload = new Map<String, Object>();
            userPayload.put('email', user.Email);
            userPayload.put('leftoverVacationDays', usersMap.get(user.Id).Leftover_Vacation__c);
            userPayloads.add(userPayload);
        }
        
        // Callout to ERP system to update vacation balance for all users
            HttpRequest req = new HttpRequest();
            req.setEndpoint(getLeavePolicyConfigs().ERPIntegrationServiceURL__c);
            req.setMethod('POST');
            req.setHeader('Content-Type', 'application/json');
            req.setBody(JSON.serialize(userPayloads));
            
            Http http = new Http();
            HttpResponse res = http.send(req);
            
            if (res.getStatusCode() != 200) {
                System.debug('Failed to update ERP system: ' + res.getBody());
            }

        }

        @TestVisible
        private static Leave_Policy_Config__mdt getLeavePolicyConfigs() {
            return [SELECT Id, MaximumLeaveDurationinDays__c, TotalVacationDaysPerYear__c, ERPIntegrationServiceURL__c 
                    FROM Leave_Policy_Config__mdt LIMIT 1];
        }
    }